[tool.poetry]
name = "moleCad"
version = "0.1.0"
description = ""
authors = ["vvrubel <vasilyeva1510@gmail.com>"]

[[tool.poetry.source]]
name = "biocad"
url = "https://pypi.net.biocad.ru"
secondary = true

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
pubchempy = "^1.0.4"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
