[tool.poetry]
name = "molecad"
version = "0.1.0"
description = "download molecules using pubchem api"
authors = ["vvrubel <vasilyeva1510@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.25.1"
pubchempy = "^1.0.4"
loguru = "^0.5.3"
pydantic = "^1.8.2"
flake8 = "^3.9.2"
typing-extensions = "^3.10.0"
click = "^8.0.1"
fire = "^0.4.0"
pymongo = "^3.11.4"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
flake8 = "^3.9.2"
isort = "^5.8.0"
black = "^21.6b0"
mypy = "^0.902"

[tool.black]
line-length = 100
target_version = ['py39']

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
