[tool.poetry]
name = "molecad"
version = "0.1.0"
description = ""
authors = ["vvrubel"]
license = "free"

[tool.poetry.dependencies]
python = "3.7"
mongordkit = {git = "git@github.com:rdkit/mongo-rdkit.git"}

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
